server:
  port: 9090

spring:
  application:
    name: rest

# Eureka configuration
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9081/eureka/
  instance:
    preferIpAddress: true
