server:
  port: 9085

spring:
  application:
    name: auth

security:
  oauth2:
    resource:
      filter-order: 3

auth:
  jwt:
    token:
      key:
        path: D:\my-projects\SpringCloud\_keys\authorization.p12
        password: "***"
        alias: services-authorization

# Eureka configuration
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9081/eureka/
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 10
