server:
  port: 9081

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    enableSelfPreservation: true
    eviction-interval-timer-in-ms: 1000

management:
  endpoints:
    configprops:
      enabled: true
    web:
      exposure:
        include: info,health,configprops,metrics
